### ISSUE TITLE
Practice trials

### ISSUE THREAD

**Issue by iyildirim** [CNCLgithub/per_rf#13]
We need 5 practice trials to get the subjects accustomed to the experiment parameters.

**Comment by belledon** [comment]
do we have spare metamers?
or can these just be random images?

**Comment by hakanyi** [comment]
We do have spare metamers: The four remaining after we select 6 out of 10 images for the actual experiment.

**Comment by iyildirim** [comment]
Indeed and just discussed the details with @belledon -- let's use images 7 and 8 and show pairs of metamers. 0.3 vs 0.4 and 0.3 vs 0.5 for each image making a total of 4 practice trials. It's okay if we have 3 practice trials as well.

**Comment by belledon** [comment]
great!
@hakanyi ,
Is there any chance you can create a json with the following format:

```json
[
  # trial i
  {
    "first": "fileA",
    "second": "fileB",
    "third": "[first,second]", # indicates which of the previous images goes third
  }
]
```

It should be 120 elements

**Comment by iyildirim** [comment]
In general, we should write scripts of this sort in Python as a preferred language when possible and practical. This also applies to the analysis codes we will write.
