### ISSUE TITLE
Add mask and adjust presentation times

### ISSUE THREAD

**Issue by iyildirim** [CNCLgithub/per_rf#14]
Use this image to implement the protocol

![image](https://user-images.githubusercontent.com/4510285/64871793-faaee780-d613-11e9-9bff-4515e8985151.png)

**Comment by belledon** [comment]
@iyildirim ,

Can you pull from b80e087  and take a look? I don't think the credit card has the proper dimensions

**Comment by iyildirim** [comment]
You're right that the credit card doesn't have the right dims. I was planning to change it and will do soon.

Can I just pull the pilot branch?

**Comment by belledon** [comment]
yes

**Comment by iyildirim** [comment]
Awesome!
