### ISSUE TITLE
Recording data on the server?

### ISSUE THREAD

**Issue by iyildirim** [CNCLgithub/per_rf#20]
Are we recording any data at all on the server side? I think we need to flip some of those `datacommit: false` statements. @belledon can you take a look at that? We can't depend on subjects downloading and sending along their data.

**Comment by belledon** [comment]
`datacommit` has nothing to do with saving data to the database. It just
means we don't care about that row of data.

I think we need more information from Al about how data will be stored.
When they asked about which columns I assumed that they had a system to
automatically save the data and parse out the required bits.

There is also this link in the docs but I'm hesitant to start working on it
until we here back from Al.

https://labjs.readthedocs.io/en/latest/learn/deploy/index.html

**Comment by iyildirim** [comment]
Sounds good
