### ISSUE TITLE
MTurk study

### ISSUE THREAD

**Issue by iyildirim** [CNCLgithub/per_rf#21]
We need to run an MTurk study as our control pool. Would it be hard to integrate this with psiturk? Or should we just use AWS API directly? Or should we re-implement the exp in psiturk?

**Comment by iyildirim** [comment]
We can instead use qualtrics -- seems lab.js can be readily integrated

https://labjs.readthedocs.io/en/latest/learn/deploy/3a-qualtrics.html

**Comment by belledon** [comment]
I just sent out an email to Al,
Given that he wanted us to use the Builder and export the study, I really think he would be handling data collection on his end. Did you receive any updates that I may not have?

**Comment by hakanyi** [comment]
It seems that we have at least two options here - either we pursue the integration into Qualtrics or into Yale Redcap (possibly integrated into the entire Yale/AWS Lambda framework Chris informed us about). @iyildirim, in both cases we'd need to setup accounts that I'm happy to take the lead on or help you with. I think setting up Redcap is the most sustainable solution though as a) we have exhaustive instructions on how to set it up and b) we're HIPAA compliant for relevant future experiments/data.
