### ISSUE TITLE
add proper experimental parameters

### ISSUE THREAD

**Issue by belledon** [CNCLgithub/per_rf#4]

**Comment by belledon** [comment]
@iyildirim ,
Can you pull and take a look?

**Comment by iyildirim** [comment]
Looks good. Here are some comments.

-- THe second screen is using a keyboard where the keys "R", "G", "B", and "O" are highlighted. Why is that?

-- The question on the screen says "Was the third image the same as first (f) or second (j)?", which is good. But then the text at the bottom says "Did the third image match the first (f) or the second (j)?" which asks the same thing but with (slightly) different words which can be confusing. Can we instead say at the bottom just "First image (f), second image(s)"?

-- I am seeing only two images presented as opposed to 3.

-- I'll post edits on the first screen's words.

**Comment by iyildirim** [comment]
Can you add me as a collaborator so that I can push?

**Comment by iyildirim** [comment]
And after I push, please go through the 1-welcome.html text once again and do your edits and let me know.

**Comment by belledon** [comment]
can you reference this issue in your commit message so I know when you're done?

**Comment by belledon** [comment]
Thanks for the other comments, I'll fix that

**Comment by belledon** [comment]
also I'm assuming you figured this out, but this is your repo now more or less. I don't have the power to add collaborators

**Comment by iyildirim** [comment]
I added myself, but I believe you should have the right permissions now.

**Comment by iyildirim** [comment]
Sorry I had already wrote my commit message before I saw your thing about referencing. I pushed my changes.

**Comment by belledon** [comment]
give it another shot

**Comment by iyildirim** [comment]
Okay.

Why am I still seeing "R", "G", "B", "O" highlighted on the keyboard screen?

**Comment by iyildirim** [comment]
Okay this looks good otherwise.

@hakanyi any updates on the metameric images using FS's matlab codebase? Thanks

**Comment by belledon** [comment]
i need to make a new image for that

**Comment by iyildirim** [comment]
Sounds good - let me know when you have it. It should highlight f and j

**Comment by hakanyi** [comment]
@iyildirim Working on it, will update you soon

**Comment by iyildirim** [comment]
@belledon 

We need an introduction slide where we tell subjects that they need to be at an arm's length distance from the monitor.

Is it possible to read-off the resolution of the user's screen to ensure we will present the images that will subtend 26degx26deg? 

This is what the authors did "Images were rendered at 512×512 px, and we fixed the monitor at 52cm viewing distance and 800×600px resolution so that the stimuli subtended 26deg×26deg."

52cm is about an arm's length distance so it's fine.

**Comment by belledon** [comment]
i'll look into this

**Comment by hakanyi** [comment]
@iyildirim Which model did you use to compute the metamers, the square (fast, approximative) or radial (slow, actual model used by FS)? Using the default 50 iterations, The former takes 6 min for one image and the latter ~5 min for **one iteration**, i.e. ~2.5 h for one image. Used my i7-4600U with 2 physical cores and standard parameters.

**Comment by iyildirim** [comment]
We should do the radial bases. Can you request an account on Milgram using this https://research.computing.yale.edu/support/hpc/account-request? It's basically identical to how OM works. It has a lot of CPUs on it, which is what we need here to parallelize things.

**Comment by hakanyi** [comment]
Alright, sounds good! I'll prepare the scripts and as soon as I have access, we'll be ready to go.
Are the following parameters right? radial, scales=[0.25, 0.35, 0.45, 0.55, 0.65], aspect=2 with 50 iterations for gray and color images, i.e. **2x10 images x 5 parameters = 100 metamers**.

**Comment by iyildirim** [comment]
What is apect?

**Comment by iyildirim** [comment]
And yes for the rest.

**Comment by iyildirim** [comment]
I see. Yes, use 2. The paper says
"For each choice of scaling, we chose an integer number of polar-angle windows (Nθ) that yielded an aspect ratio of radial width to circumferential width of approximately 2."

**Comment by belledon** [comment]
yes, see #6
