### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by iyildirim** [CNCLgithub/per_rf#6]
What do we need to publish the experiment?

Share with Al:
- [x] Json file coming from lab.js when you save it (I don't know what this means)
- [ ] Zipped directory when you say "export for local use" at the end
- [ ] Names of variables we want to be recorded

**Comment by iyildirim** [comment]
- [ ] All 50 grayscale images; we will then need to choose 6*5=30 of them.

@belledon do you know what "the json file coming from lab.js when you save it" from Al's email means? If not, we should ask for clarification.

**Comment by belledon** [comment]
now i'm a little confused about the trials.
If we randomize the presentation order within trial (ABC, BCA...) then we will have allot of trials...

Instead of having each trial repeat 20 times lets do 18,

for eachh unique collection of metamers, we will have 6 unique orderings, and if we repeat each arrangement 3 times we will have 30 * 6 * 3 = 540 trials (I'm really not sure we want to repeat at all)...

**Comment by iyildirim** [comment]
There are four possible orderings

ABA
ABB
BAA
BAB

where A is a reference item and B is a synthesized item.

We should have the base 30 pairs (6 ref images paired with each of their 5 synthesized metamers). Each pair will be presented 20 times. But at each time we are presenting a pair, we randomly draw whether it goes "AB" or "BA" as the first two images and then whether "A" or "B" follows as the third image. 

Repeat presentations are fine - as far as I can tell this what both F&S paper and Neurofoveation papers do.

**Comment by belledon** [comment]
Ah i see..

I still think we should just define the ordering apriori. 

Labjs allows us to stipulate how many randomly shuffled loops we can go through, so we just need to define the 30 x 4 (120) trial list and loop through it 5 times with a random order each iteration.

**Comment by iyildirim** [comment]
This sounds good to me.

**Comment by hakanyi** [comment]
Why not define the entire 30 x 20 trial list a priori and "loop" through it once?

**Comment by belledon** [comment]
we will have less order effects that way

**Comment by belledon** [comment]
also I already implemented it so

**Comment by iyildirim** [comment]
Please update when images are integrated with the new trial list.

**Comment by belledon** [comment]
@iyildirim ,

Had issue with the fullscreen (see the corresponding page in `pages`).

The counter goes to the right of the screen for some reason...

**Comment by iyildirim** [comment]
I'm okay with counter going to the right of the screen. It was initially distracting but then it never bothered after a few trials. It's also good that it goes to right because most laptops have width > height.

Should I take a stab at fullscreen?

**Comment by iyildirim** [comment]
@belledon  and @hakanyi: can you address what Al wants (see the top of this thread) and prepare an email draft here or over the email? I think we are ready except those things at the top. Thanks.

**Comment by belledon** [comment]
email draft:

Please see the release (https://github.com/CNCLgithub/per_rf/archive/v0.1.zip) of our experiment. This should be able to run by using node (ie `http-server`). All media needed should be included in the release.

While it would be ideal to get all columns back from labjs, the minimum set would be:
sender_id, correct, duration, first, second, third"
